name: Lint with Ruff
on:
  workflow_run:
    workflows: ["Format with black"]
    types:
      - completed

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
